GET http://localhost:3000/players/
###

GET http://localhost:3000/players/1/
###

POST http://localhost:3000/players/ 
Content-Type: application/json
{
    "playerName":"Vishal",
    "jerseyName":17,
    "role": "Bowler"
}
###

PUT http://localhost:3000/players/1/
Content-Type: application/json
{
    "playerName":"Vishal",
    "jerseyName":17,
    "role": "Bowler"
}
###